version: '2'
services:
  hbase:
    build: ./hbase
    image: hbase
    network_mode: "bridge"
    hostname: hbase-docker
    ports:
      - "2181:2181"
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
  kafka:
    depends_on:
      - hbase
    build: ./kafka-broker
    network_mode: "bridge"
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      - ZK_IPS=${DOCKER_MACHINE_IP}:2181
      - ADVERTISED_HOST_NAME=${DOCKER_MACHINE_IP}
      - BROKER_ID=1
      - CLUSTER_NAME=test
