version: '2'
services:
  hdfs:
    build: ./hdfs
    container_name: "dfs"
    command: "dfs"
    network_mode: "bridge"
    ports:
      - "8020:8020"
      - "50070:50070"
      - "50010:50010"
      - "50020:50020"
      - "50075:50075"
