version: '2'
services:
  hdfs:
    build: ./hdfs
    container_name: "dfs"
    network_mode: "bridge"
    ports:
      - "1004:1004"
      - "1006:1006"
      - "8022:8022"
      - "9000:9000"
      - "50010:50010"
      - "50020:50020
      - "50075:50075"
