version: '2'
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ZK_ID=1
      - ZK_SERVERS=192.168.99.100:2181
  kafka:
    depends_on:
      - zookeeper
    build: ./kafka-broker
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      - ZK_IPS=zookeeper:2181
      - ADVERTISED_HOST_NAME=192.168.99.100
      - CLUSTER_NAME=test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
