version: '2'
services:
  yarn:
    build: ./hadoop
    image: hadoop
    container_name: "yarn"
    command: "yarn"
    network_mode: "bridge"
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8041:8041"
      - "8042:8042"
      - "8088:8088"
